export { RenaperService } from './ws/renaper.service';
export { RRHHService } from './ws/rrhh.service';
export { SubirArchivosService } from './subirArchivo/subir-archivos.service';
export { LoginGuardGuard } from './guards/login-guard.guard';
export { SettingsService } from './settings/settings.service';
export { SharedService } from './shared/shared.service';
export { SidebarService } from './shared/sidebar.service';
export { UsuarioService} from './usuario/usuario.service';
export {EdificioService } from './edificio/edificio.service';
export {PersonaService} from './persona/persona.service';
